# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A blog where I put stuff that I dont want to google again. '
url:              https://xapax.github.io
baseurl:          /blog/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
