# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Devhack
tagline:          "Stuff I don't want to google again"
description:      "A blog where I put stuff that I don't want to google again. "
url:              https://xapax.github.io
baseurl:          /blog/
posturl:          /blog

author:
  name:           'Philip Linghammar'
  url:            https://xapax.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/xapax
